name: 'Publish new release'

on:
  push:
    branches:
      - main

jobs:
  publish-socket-server:
    name: Build and publish socker server docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./threeJS_memory/server/Dockerfile
          push: true
          tags: juliengery/socket-server:latest
