name: 'Publish new release client'

on:
  push:
    branches:
      - main

jobs:
  publish-web-client:
    name: Build and publish web client docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ./threeJS_memory
          file: ./threeJS_memory/Dockerfile
          push: true
          tags: ghcr.io/juliengery/web-client:latest
